name: Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Clone folly
      run: git clone https://github.com/facebook/folly
    - name: Install folly
      run: cd folly && sudo ./build/fbcode_builder/getdeps.py install-system-deps --recursive
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: xmake
      run: xmake -y
